stages:
    # - deploy_static
    - deploy_dev

default:
    image: alpine:3.15.0
    cache:
        key:
            files:
                - frontend/yarn.lock
        paths:
            - frontend/node_modules/

.install_deps:
    before_script:
        # install git to get dependencies from github
        - apk --update add git
        - cd frontend
        - yarn install

.setup_ssh:
    before_script:
        - apk add --update openssh rsync
        - eval $(ssh-agent -s)
        - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan -H $SSH_DEV_HOST >> ~/.ssh/known_hosts

# build_static:
#     image: node:20.2.0-alpine3.17
#     extends:
#         - .install_deps
#     stage: deploy_static
#     script:
#         - yarn build
#     when: manual
#     # artifacts are passed only between stages and dependent jobs
#     artifacts:
#         paths:
#             - frontend/build
#         expire_in: 5 minutes

# deploy_static:
#     extends:
#         - .setup_ssh
#     stage: deploy_static
#     needs:
#         - build_static
#     script:
#         - |
#           rsync -ra --delete \
#           frontend/build $SSH_DEV_USER@$SSH_DEV_HOST:$SSH_DEV_PATH

deploy_dev:
    extends:
        - .setup_ssh
    stage: deploy_dev
    when: manual
    script:
        - ssh $SSH_DEV_USER@$SSH_DEV_HOST "cd $SSH_DEV_PATH && git pull origin master && make migrations-dev"
